# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: skynet.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='skynet.proto',
  package='skynet',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cskynet.proto\x12\x06skynet\";\n\x0c\x44oubleMatrix\x12\x0c\n\x04rows\x18\x01 \x01(\r\x12\x0f\n\x07\x63olumns\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x01\":\n\x0b\x46loatMatrix\x12\x0c\n\x04rows\x18\x01 \x01(\r\x12\x0f\n\x07\x63olumns\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x03(\x02\"\xab\x01\n\x11SparseFloatMatrix\x12\x0c\n\x04rows\x18\x01 \x01(\r\x12\x0f\n\x07\x63olumns\x18\x02 \x01(\r\x12\x38\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32*.skynet.SparseFloatMatrix.FloatMatrixEntry\x1a=\n\x10\x46loatMatrixEntry\x12\x0b\n\x03row\x18\x01 \x01(\r\x12\x0e\n\x06\x63olumn\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x01\"\xaf\x01\n\x12SparseDoubleMatrix\x12\x0c\n\x04rows\x18\x01 \x01(\r\x12\x0f\n\x07\x63olumns\x18\x02 \x01(\r\x12:\n\x04\x64\x61ta\x18\x03 \x03(\x0b\x32,.skynet.SparseDoubleMatrix.DoubleMatrixEntry\x1a>\n\x11\x44oubleMatrixEntry\x12\x0b\n\x03row\x18\x01 \x01(\r\x12\x0e\n\x06\x63olumn\x18\x02 \x01(\r\x12\x0c\n\x04\x64\x61ta\x18\x03 \x01(\x01\x62\x06proto3'
)




_DOUBLEMATRIX = _descriptor.Descriptor(
  name='DoubleMatrix',
  full_name='skynet.DoubleMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='skynet.DoubleMatrix.rows', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='columns', full_name='skynet.DoubleMatrix.columns', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='skynet.DoubleMatrix.data', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=83,
)


_FLOATMATRIX = _descriptor.Descriptor(
  name='FloatMatrix',
  full_name='skynet.FloatMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='skynet.FloatMatrix.rows', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='columns', full_name='skynet.FloatMatrix.columns', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='skynet.FloatMatrix.data', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=143,
)


_SPARSEFLOATMATRIX_FLOATMATRIXENTRY = _descriptor.Descriptor(
  name='FloatMatrixEntry',
  full_name='skynet.SparseFloatMatrix.FloatMatrixEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='skynet.SparseFloatMatrix.FloatMatrixEntry.row', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column', full_name='skynet.SparseFloatMatrix.FloatMatrixEntry.column', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='skynet.SparseFloatMatrix.FloatMatrixEntry.data', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=256,
  serialized_end=317,
)

_SPARSEFLOATMATRIX = _descriptor.Descriptor(
  name='SparseFloatMatrix',
  full_name='skynet.SparseFloatMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='skynet.SparseFloatMatrix.rows', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='columns', full_name='skynet.SparseFloatMatrix.columns', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='skynet.SparseFloatMatrix.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SPARSEFLOATMATRIX_FLOATMATRIXENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=146,
  serialized_end=317,
)


_SPARSEDOUBLEMATRIX_DOUBLEMATRIXENTRY = _descriptor.Descriptor(
  name='DoubleMatrixEntry',
  full_name='skynet.SparseDoubleMatrix.DoubleMatrixEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='row', full_name='skynet.SparseDoubleMatrix.DoubleMatrixEntry.row', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='column', full_name='skynet.SparseDoubleMatrix.DoubleMatrixEntry.column', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='skynet.SparseDoubleMatrix.DoubleMatrixEntry.data', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=433,
  serialized_end=495,
)

_SPARSEDOUBLEMATRIX = _descriptor.Descriptor(
  name='SparseDoubleMatrix',
  full_name='skynet.SparseDoubleMatrix',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='rows', full_name='skynet.SparseDoubleMatrix.rows', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='columns', full_name='skynet.SparseDoubleMatrix.columns', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='skynet.SparseDoubleMatrix.data', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_SPARSEDOUBLEMATRIX_DOUBLEMATRIXENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=320,
  serialized_end=495,
)

_SPARSEFLOATMATRIX_FLOATMATRIXENTRY.containing_type = _SPARSEFLOATMATRIX
_SPARSEFLOATMATRIX.fields_by_name['data'].message_type = _SPARSEFLOATMATRIX_FLOATMATRIXENTRY
_SPARSEDOUBLEMATRIX_DOUBLEMATRIXENTRY.containing_type = _SPARSEDOUBLEMATRIX
_SPARSEDOUBLEMATRIX.fields_by_name['data'].message_type = _SPARSEDOUBLEMATRIX_DOUBLEMATRIXENTRY
DESCRIPTOR.message_types_by_name['DoubleMatrix'] = _DOUBLEMATRIX
DESCRIPTOR.message_types_by_name['FloatMatrix'] = _FLOATMATRIX
DESCRIPTOR.message_types_by_name['SparseFloatMatrix'] = _SPARSEFLOATMATRIX
DESCRIPTOR.message_types_by_name['SparseDoubleMatrix'] = _SPARSEDOUBLEMATRIX
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DoubleMatrix = _reflection.GeneratedProtocolMessageType('DoubleMatrix', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLEMATRIX,
  '__module__' : 'skynet_pb2'
  # @@protoc_insertion_point(class_scope:skynet.DoubleMatrix)
  })
_sym_db.RegisterMessage(DoubleMatrix)

FloatMatrix = _reflection.GeneratedProtocolMessageType('FloatMatrix', (_message.Message,), {
  'DESCRIPTOR' : _FLOATMATRIX,
  '__module__' : 'skynet_pb2'
  # @@protoc_insertion_point(class_scope:skynet.FloatMatrix)
  })
_sym_db.RegisterMessage(FloatMatrix)

SparseFloatMatrix = _reflection.GeneratedProtocolMessageType('SparseFloatMatrix', (_message.Message,), {

  'FloatMatrixEntry' : _reflection.GeneratedProtocolMessageType('FloatMatrixEntry', (_message.Message,), {
    'DESCRIPTOR' : _SPARSEFLOATMATRIX_FLOATMATRIXENTRY,
    '__module__' : 'skynet_pb2'
    # @@protoc_insertion_point(class_scope:skynet.SparseFloatMatrix.FloatMatrixEntry)
    })
  ,
  'DESCRIPTOR' : _SPARSEFLOATMATRIX,
  '__module__' : 'skynet_pb2'
  # @@protoc_insertion_point(class_scope:skynet.SparseFloatMatrix)
  })
_sym_db.RegisterMessage(SparseFloatMatrix)
_sym_db.RegisterMessage(SparseFloatMatrix.FloatMatrixEntry)

SparseDoubleMatrix = _reflection.GeneratedProtocolMessageType('SparseDoubleMatrix', (_message.Message,), {

  'DoubleMatrixEntry' : _reflection.GeneratedProtocolMessageType('DoubleMatrixEntry', (_message.Message,), {
    'DESCRIPTOR' : _SPARSEDOUBLEMATRIX_DOUBLEMATRIXENTRY,
    '__module__' : 'skynet_pb2'
    # @@protoc_insertion_point(class_scope:skynet.SparseDoubleMatrix.DoubleMatrixEntry)
    })
  ,
  'DESCRIPTOR' : _SPARSEDOUBLEMATRIX,
  '__module__' : 'skynet_pb2'
  # @@protoc_insertion_point(class_scope:skynet.SparseDoubleMatrix)
  })
_sym_db.RegisterMessage(SparseDoubleMatrix)
_sym_db.RegisterMessage(SparseDoubleMatrix.DoubleMatrixEntry)


# @@protoc_insertion_point(module_scope)
